### ISSUE TITLE
Washing Blood Stained Shoes Doesnt Remove Blood Overlay

### ISSUE THREAD

**Issue by wesoda25** [KeplerStation/KeplerStation#1024]
Issue reported from  Round ID: 184 (KeplerStation)

Reporting client version: 512

Get shoes bloody. Wash them in sink. Shoe sprite remains bloody, but on person sprite is clean, and doesn't leave a trail.

**Comment by AffectedArc07** [comment]
This was forgotten when I did the blood rework. Will fix soon.

**Comment by AffectedArc07** [comment]
![KPb5SfmErw](https://user-images.githubusercontent.com/25063394/68996146-0c1fa480-088e-11ea-9ed1-f3aa65b1b29c.gif)
Cannot reproduce

**Comment by wesoda25** [comment]
black shoes I used chef sink if it helps?

**Comment by wesoda25** [comment]
Also I believe it was monkey blood, which might be the issue

**Comment by AffectedArc07** [comment]
Tried with monkey blood using the chef sink, still cannot reproduce.

**Comment by AffectedArc07** [comment]
Closed as this is not reproducible, and a PR has been merged which I believe fixes this.
