### ISSUE TITLE
Aheal doesn't restore broken bones

### ISSUE THREAD

**Issue by Sikroth** [KeplerStation/KeplerStation#1138]
Round ID: None, local test server

Reproduction:
- Get Broken bones anywhere
- Admin Rejuvenate yourself
- See how your bones are still broken

Picture of proof: 
![aheal bones](https://user-images.githubusercontent.com/7857084/69406697-f9302880-0d02-11ea-8e28-1e217fc5411a.png)

**Comment by AffectedArc07** [comment]
Forgot to add this, will fix soon
