### ISSUE TITLE
You can continue to use a held item after your limb is disabled

### ISSUE THREAD

**Issue by Sikroth** [KeplerStation/KeplerStation#1139]
Round ID: None, local test server

Reproduction:
- Hold an item you can use to attack things 
- Have the limb holding the item disabled via direct damage (I imagine normal disablers work the same, but I tested hitting myself with brute to disable the limb)
- See how you are still holding the item and are able to attack with it

Edit: my method often results in you eventually dropping the item because of broken bones, but the disabling itself doesn't cause the item to drop.

Picture of proof:
![disable](https://user-images.githubusercontent.com/7857084/69406851-588e3880-0d03-11ea-8a19-807476a824a9.png)
A - Animation of me hitting the window with a baton
B - my disabled limb
C - the baton being held in the disabled hand

**Comment by AffectedArc07** [comment]
Need to add force dropping when a limb is disabled

**Comment by AffectedArc07** [comment]
```dm
/obj/item/bodypart/r_arm/set_disabled(new_disabled)
	. = ..()
	if(disabled == new_disabled)
		return
	if(disabled == BODYPART_DISABLED_DAMAGE)
		if(owner.stat > UNCONSCIOUS)
			owner.emote("scream")
		if(. && (owner.stat > DEAD))
			to_chat(owner, "<span class='userdanger'>Your [name] is too damaged to function!</span>")
		if(held_index)
			owner.dropItemToGround(owner.get_item_for_held_index(held_index)) <-----------
	else if(disabled == BODYPART_DISABLED_PARALYSIS)
		if(. && (owner.stat > DEAD))
			to_chat(owner, "<span class='userdanger'>You can't feel your [name]!</span>")
			if(held_index)
				owner.dropItemToGround(owner.get_item_for_held_index(held_index)) <-----------
	if(owner.hud_used)
		var/obj/screen/inventory/hand/R = owner.hud_used.hand_slots["[held_index]"]
		if(R)
			R.update_icon()

```
They should be dropping the item anyway. Are you manually picking the item up again after?

**Comment by Sikroth** [comment]
Nah, once the item is on the floor your hand is unusable. But at least for me the item wasn't dropping when the limb was disabled, it stayed inhand. It did drop shortly after because of broken bones. I'll see if I can test with a disabler somehow in a bit.

**Comment by Sikroth** [comment]
Yeah disabler shots do not cause you to drop items at all. I shot at a guy with an item until the gun ran out, jumped at them and surely enough the arm was disabled and they were still holding and able to use the hatchet

![disabler2](https://user-images.githubusercontent.com/7857084/69459935-2caa9b80-0d73-11ea-8610-350aa3200822.png)

**Comment by AffectedArc07** [comment]
Fixed in an upstream merged PR
