### ISSUE TITLE
Some botany items are spriteless

### ISSUE THREAD

**Issue by Sikroth** [KeplerStation/KeplerStation#1210]
Issue reported from  Round ID: 196 (KeplerStation)

Reporting client version: 512

Bee balms, exotic bananas/banana spiders, and Honey Bee Balm or whatever its name is (the mutation of bee balms), all these lack sprites.

![image](https://user-images.githubusercontent.com/7857084/69992720-9d5b7000-154a-11ea-82b3-7ce54cfeb9ad.png)

**Comment by AffectedArc07** [comment]
![image](https://user-images.githubusercontent.com/25063394/72682769-9b347d00-3ac8-11ea-85f9-8abafb6b2714.png)

No longer an issue
