### ISSUE TITLE
Vents' output is almost negligible regardless of settings

### ISSUE THREAD

**Issue by Sikroth** [KeplerStation/KeplerStation#1211]
Issue reported from  Round ID: 196 (KeplerStation)

Reporting client version: 512

A simple breach can leave an area unbreathable for pretty much the rest of the round even after being fixed. I first thought the issue was that atmos is not set up and the distro pipes empty and can't carry enough air, but after maxing everything in Atmos, and having a pressure in the thousands across the distribution loop, I discovered that vents in fact move a minuscle amount of air. This is true even if you set their target pressure to the max (+5000kPa), or if you set ther internal target to 0 (so they always try to empty the pipes, which should mean max output), or both.

Attached is a picture of the air alarm a few tiles away from a maxed pump showing no difference in pressure almost whatsoever. You'd expect a max pressure vent connected to a full distro would expel an amout of air that'd *maybe* create some sort of air current, but nope.

![image](https://user-images.githubusercontent.com/7857084/69994625-89197200-154e-11ea-9056-56f08ea8dfe5.png)

**Comment by Sikroth** [comment]
To be honest, I believe this might be just the way tg handles atmos, but coming from paradise where maxing a vent instantly overpressurizes the room and you can actually refill rooms before dying from boredom, our version is pretty underwhelming.

**Comment by Alonefromhell** [comment]
This is because of the settings in the atmos department. If those were maxed out, for example, it would refill *much* faster.

**Comment by AffectedArc07** [comment]
@Sikroth @Alonefromhell is this an actual bug or just bad game design

**Comment by Alonefromhell** [comment]
@AffectedArc07 afaik, everything in atmos is set to ~101, so i wouldn't say it's a bug, no

**Comment by Sikroth** [comment]
Late reply because I forgot to check here. I maxed the piping in atmos. From the Oxy/N2 tanks to the Air and then to the Distro pipes. The distribution loop had over 1000 kPa when I tested this and raising. Should be enough to actually make a maxed vent *do something*, which it barely did. Definitely did not move any more air than the default 101 kpa setting.

**Comment by AffectedArc07** [comment]
Im going to declare this not a bug because the `Target Pressure` is just what the vent will stop pressurising the room at, if you think logically, it shouldnt make it faster, just make it run for longer
