### ISSUE TITLE
LOOC hotkey doesnt work

### ISSUE THREAD

**Issue by AffectedArc07** [KeplerStation/KeplerStation#170]
Issue reported from  Round ID: 48 (KeplerStation)

Reporting client version: 512

Pressing L does not bring up LOOC. Probably got borked in #157. @lass9030 could you look at this when you can?

**Comment by lass9030** [comment]
Will do, cappy.

**Comment by AffectedArc07** [comment]
You have to be in hotkey mode, **AND** the hotkey control set in character options
![image](https://user-images.githubusercontent.com/25063394/60656244-09746380-9e47-11e9-830f-73848ad36f73.png)
