### ISSUE TITLE
*squish doesn't work and other emote mishaps

### ISSUE THREAD

**Issue by Sikroth** [KeplerStation/KeplerStation#194]
## Round ID:

I think it was 54, seeing it just finished and it's at 55 now.

## Testmerges:

Unsure, but it's probably related to the recently merged #184

## Reproduction:

1. Be a roundstart slimeperson
2. Try to *squish
3. You can't, sadly. Chat doesn't say anything about it being an invalid emote though.
4. Frustrated, try to *buzz instead
5. It works.

So yeah, all the other robotic noises seem to work as well. There's also a *peep emote to do a birdlike sound but it sounds like you could whistle that so it's not too weird I guess. And a *msqueak to... squeak like a noise. Both useable as a slimeperson, unsure if other species can.

**Comment by AffectedArc07** [comment]
@CornMyCob
