### ISSUE TITLE
Head of security spawns in robotics on OmegaStation

### ISSUE THREAD

**Issue by AffectedArc07** [KeplerStation/KeplerStation#257]
Issue reported from  Round ID: 68 (KeplerStation)

Reporting client version: 512

Had to teleport the head of security from robotics into the bridge at roundstart. This is a pretty big issue

**Comment by Alonefromhell** [comment]
I have a fix for this. I'll do a couple of the other OmegaStation specific ones, then i'll throw up a PR.
