### ISSUE TITLE
Acute Blood Deficiency doesn't work on slimepeople

### ISSUE THREAD

**Issue by Sikroth** [KeplerStation/KeplerStation#259]
Issue reported from  Round ID: 69 (KeplerStation)

Reporting client version: 512

The Acute Blood Deficiency quirk should slowly reduce the blood level of the person. However it seems to do absolutely nothing currently when you play as a slimepeople, so it's just a free +2 quirk balance. Unsure if this is related to how species work in kepler or if it's an upstream issue, too.

Note: while I've been told that it does work in regular humans, I haven't tested this myself.

**Comment by lolman360** [comment]
Intended. Actute _**Blood**_ deficiency only works with blood. It's a free -2 points on plasmaman, slime, anything without/with nonstandard blood.
