### ISSUE TITLE
Jellypeople can't squish

### ISSUE THREAD

**Issue by Sikroth** [KeplerStation/KeplerStation#384]
Xenobiology based Jellypeople species can't use the *squish emote despite being made from slimes and looking slimey.

This includes default Jellypeople, as well as the subspecies: Stargazer, Luminescent and Xenobiological Slimeperson.

## Steps to reproduce

1. Get slime mutation toxin from xenobio
2. Mutate to jellypeople (or the subspecies)
3. Try to *squish and be told your species can't do that

**Comment by AffectedArc07** [comment]
Probably forgot it in #332
