### ISSUE TITLE
Object and nonbinary gender still exist

### ISSUE THREAD

**Issue by AffectedArc07** [KeplerStation/KeplerStation#435]
Issue reported from  Round ID: 85 (KeplerStation)
![image](https://user-images.githubusercontent.com/25063394/62733305-36a3cb00-ba1e-11e9-84e5-158170336cd7.png)

This shouldnt exist

Reporting client version: 512

**Comment by Shadeykins** [comment]
Wait

Object?

wat.

**Comment by Shadeykins** [comment]
Looking it over, this is potentially hooked in quite a few places. May be best to try and strip out the selection in its entirety and simply leave the deprecated references intact (since there's 500+ of them).

**Comment by Sikroth** [comment]
I don't have a problem with non binary but I feel like trying to argue in favor of it is prooobably going to open a debate I do not intend to have in here.

Object though, that's just funny.
