### ISSUE TITLE
AI speaking through holopad issue.

### ISSUE THREAD

**Issue by Alonefromhell** [KeplerStation/KeplerStation#480]
Round ID: 99 (and before)

Issue:
People around the holopad are unable to hear your words, they simply hear "a weird noise" (not exact words).

Reproduction:
Speak as AI through the holopads.

If anyone could comment below what it sounds like on the other side, that would be helpful.

**Comment by Sikroth** [comment]
The exact line is, _AIname makes a strange sound._

Usually also shows in small font for whatever reason, from what I recall.
