### ISSUE TITLE
Reinforced directional windows cannot be deconstructed or attacked

### ISSUE THREAD

**Issue by MrJWhit** [KeplerStation/KeplerStation#521]
## Testmerges:

 oracleUI that I know of

## Reproduction:

At the time, I was a bit busy being a traitor, but I couldn't attack them or deconstruct them in the captains office. This was with power tools, which could remove full windows no problem.

**Comment by AffectedArc07** [comment]
Update on this, also applies to windoors. they work from the inside, but you cant click them from the outside. May have broke when I bought us up to dreamchecker standards

**Comment by Sikroth** [comment]
I made a handy diagram. I believe this is how the behaviour was: You can't interact with directional windows/windoors when you stand in the direction they're facing. I'm not sure about the diagonals, I think you can't interact with it from the 3 tiles to the direction it's facing, but I'm not 100% sure.

![winnn](https://user-images.githubusercontent.com/7857084/63976172-05fd0180-cab1-11e9-83fa-5deabc93446d.png)
_(red guy can't interact with window, greens can)_
