### ISSUE TITLE
Radiation storms dont add emergency access to maintenance airlocks

### ISSUE THREAD

**Issue by AffectedArc07** [KeplerStation/KeplerStation#550]
Issue reported from  Round ID: 116 (KeplerStation)

1: See announcement for radiation storm
2: Realise youre stuck in a department and cant leave
3: Scream
![image](https://user-images.githubusercontent.com/25063394/64068487-be9d7f00-cc30-11e9-87d5-b24910120570.png)

Reporting client version: 512

**Comment by Sikroth** [comment]
I just happened to read the [Starter guide](https://tgstation13.org/wiki/Starter_guide#What_to_do_if_There.27s_a_Breach) on the tg wiki and there's a section near the bottom about hazards saying, _Radiation Storm: A message stating "High levels of radiation detected near the station. Maintenance is best shielded from radiation." will broadcast. Normally, if the heads are competent, a station-wide emergency will then be declared opening up maintenance even if you don't have access. All you have to do now is mill in maintenance until the radiation storm passes over._

Meaning it's not technically a bug, it's intended behaviour. Except with superlow pop and noone sitting in bridge I think it's fair to change it.
