### ISSUE TITLE
Unnamed Airlock in Departures

### ISSUE THREAD

**Issue by zubora** [KeplerStation/KeplerStation#590]
## Reproduction: Simply putting your mouse cursor above the airlocks reveals an unnamed airlock. To put it in perspective:

![scrnshot1](https://user-images.githubusercontent.com/9900643/64736645-7a786d00-d4c1-11e9-8da1-8523e62d5015.png)

The three white airlocks (to the left, with windows) should all be named Departures Lounge, but the top one (from top to bottom) is just named "airlock" as if it was recently built and unnamed.

**Comment by AffectedArc07** [comment]
Turns out someone had actually deconstructed and built it
