### ISSUE TITLE
Stabilized Bluespace Extract triggers on Z-Level change

### ISSUE THREAD

**Issue by Sikroth** [KeplerStation/KeplerStation#642]
Stabilized bluespace extract is supposed to teleport you to a human-safe random location when you take an amount of damage. However it seems like currently it can trigger when switching Z-levels, probably because the extract somehow loses track of the host's status and then triggers. 

This is the line to pinpoint where it happens:

The stabilized bluespace extract notices the sudden change in Iris Rosett's physical health, and activates!

EDIT: For the record we were in a escape pod (the one in arrivals, in box). And the rest of the people complained about exploding and dyiing in OOC. So perhaps this isn't a bug with the extract yeeting people but rather a bug where the escape pods fucking explode when switchign Z-levels.

## Reproduction:
- Acquire stabilized bluespace extract
- Change Z-Levels, for instance when the escape shuttle launches
- Be yeeted into space (because there's no safe-for-humans areas in the shuttle z-level, probably?)

**Comment by Alonefromhell** [comment]
On local testing, i was not able to reproduce any of this. I assume the `rest of the people` means more than 2, and they were therefore resting on the floor. It's possible that one or more got launched into both the person holding the extract, and the shuttle door - opening it - since on this codebase, the shuttle door doesn't lock after it launches.

**Comment by Sikroth** [comment]
Yeah I tried and couldn't reproduce this either. I am still not sure because I am fairly sure *something* exploded the exact moment the shuttle launched which is iffy, but local testing the stabilized bluespace extract I got nothing so it must've been something entirely different.

I'll just close this for now.
