### ISSUE TITLE
Can't extract blood from slimepeople (and subspecies) 

### ISSUE THREAD

**Issue by Sikroth** [KeplerStation/KeplerStation#980]
Issue reported from  Round ID: 178 (KeplerStation)

Reporting client version: 512

What it says in the title. Steps

- Become slime person through xenobio (or roundstart)
- use syringe on self
- "You are unable to draw any blood from Iris Rosett!x2"

**Comment by AffectedArc07** [comment]
Slimes have no blood. You must use a monkey.

**Comment by AffectedArc07** [comment]
Should be able to extract slime jelly
