### ISSUE TITLE
Health scanners don't show xenobio slimepeople "blood" %level

### ISSUE THREAD

**Issue by Sikroth** [KeplerStation/KeplerStation#984]
Issue reported from  Round ID: 181 (KeplerStation)

Reporting client version: 512

Likely thanks to the blood rework.

Xenobiological Slimepeople can split. This is achieved by reaching 200% "blood" volume (originally jelly, but functionally it's their blood level). This level showed up in health scanners before but now it's not shown. The level itself still exists and you can check it in the swap bodies window.

![jelly](https://user-images.githubusercontent.com/7857084/68335970-c0c30480-00dd-11ea-8a40-505546719f95.png)

**Comment by AffectedArc07** [comment]
This has todo with slimes having `NOBLOOD`. I am gonna add blood back to slimes eventually.
